name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: 1.8
          distribution: adopt 
      
      - name: Compile
        run: |
          cd "source code/src"
          javac *.java
          
